FROM node:24-alpine

RUN apk add imagemagick imagemagick-jpeg imagemagick-jxl imagemagick-heic imagemagick-webp unzip wget perl

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# two-step copying, so we get better caching
COPY ./package.json .
COPY ./yarn.lock .
RUN yarn install

# Copying source files
COPY . /usr/src/app/
RUN npx next telemetry disable
COPY ./docker-entrypoint.sh /usr/src/app/

# Building app
RUN npm run build
EXPOSE 3000

# Running the app
ENTRYPOINT ["sh", "/usr/src/app/docker-entrypoint.sh"]